// SIGN UP
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// SIGN IN
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

// SIGN OUT
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

// COMMON
export const SET_LOADING = "SET_LOADING";
export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// PRODUCTS
export const SET_PRODUCTS_SUCCESS = "SET_PRODUCTS_SUCCESS";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

// PRODUCT
export const SET_PRODUCT_SUCCESS = "SET_PRODUCT_SUCCESS";
export const SET_PRODUCT_ERROR = "SET_PRODUCT_ERROR";

// ADD PRODUCT
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const ADD_PRODUCT_PRODUCTS_ERROR = "ADD_PRODUCT_PRODUCTS_ERROR";

// EDIT PRODUCT
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

// DELETE PRODUCT
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const GET_AR_PRODUCTS_SUCCESS = 'GET_AR_PRODUCTS_SUCCESS';
export const GET_AR_PRODUCTS_ERROR = 'GET_AR_PRODUCTS_ERROR';

// WBTB
export const SET_WBTBS_SUCCESS = "SET_WBTBS_SUCCESS";
export const SET_WBTBS_ERROR = "SET_WBTBS_ERROR";

// WBTB ITEM
export const SET_WBTB_SUCCESS = "SET_WBTB_SUCCESS";
export const SET_WBTB_ERROR = "SET_WBTB_ERROR";

// ADD WBTB
export const ADD_WBTB_SUCCESS = "ADD_WBTB_SUCCESS";
export const ADD_WBTB_ERROR = "ADD_WBTB_ERROR";

// EDIT WBTB
export const EDIT_WBTB_SUCCESS = "EDIT_WBTB_SUCCESS";
export const EDIT_WBTB_ERROR = "EDIT_WBTB_ERROR";

// DELETE WBTB
export const DELETE_WBTB_SUCCESS = "DELETE_WBTB_SUCCESS";
export const DELETE_WBTB_ERROR = "DELETE_WBTB_ERROR";

export const GET_SOURCE_WBTBS_SUCCESS = "GET_SOURCE_WBTBS_SUCCESS";
export const GET_SOURCE_WBTBS_ERROR = "GET_SOURCE_WBTBS_ERROR";

// ULASANS
export const SET_ULASANS_SUCCESS = "SET_ULASANS_SUCCESS";
export const SET_ULASANS_ERROR = "SET_ULASANS_ERROR";

// ADD ULASAN
export const ADD_ULASAN_SUCCESS = "ADD_ULASAN_SUCCESS";
export const ADD_ULASAN_ERROR = "ADD_ULASAN_ERROR";

// DELETE ULASAN
export const DELETE_ULASAN_SUCCESS = "DELETE_ULASAN_SUCCESS";
export const DELETE_ULASAN_ERROR = "DELETE_ULASAN_ERROR";
